spring.application.name=controle-estoque

# Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/controle_estoque
spring.datasource.username=postgres
spring.datasource.password=Vortex@159

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
